CREATE TABLE books
(
    id               INTEGER GENERATED BY DEFAULT AS identity PRIMARY KEY,
    title            TEXT        NOT NULL,
    author           TEXT        NOT NULL,
    isbn             TEXT UNIQUE NOT NULL,
    genre            TEXT        NOT NULL,
    available_copies INTEGER     NOT NULL CHECK (available_copies >= 0)
);

CREATE TABLE users
(
    id       INTEGER GENERATED BY DEFAULT AS identity PRIMARY KEY,
    name     TEXT        NOT NULL,
    email    TEXT UNIQUE NOT NULL,
    password TEXT        NOT NULL,
    role     TEXT        NOT NULL
);

CREATE TABLE loans
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    book_id       INTEGER NOT NULL REFERENCES books (id) ON DELETE CASCADE,
    loan_date     DATE    NOT NULL,
    due_date      DATE    NOT NULL,
    returned_date DATE,
    price         NUMERIC(10, 2),
    CONSTRAINT price_required_if_returned CHECK (
        (returned_date IS NULL AND price IS NULL)
            OR
        (returned_date IS NOT NULL AND price IS NOT NULL)
        )
);
